retail_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', '127.0.0.1') }}"
      user: "{{ env_var('POSTGRES_USER', 'retail_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'retail_password') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'retail_db') }}"
      schema: analytics
      threads: 4